# Generated by Django 4.0.3 on 2022-04-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='litecon_address',
            new_name='litecoin_address',
        ),
    ]
