# Generated by Django 4.0.4 on 2022-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_litecon_address_customuser_litecoin_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_created',
            field=models.BooleanField(default=False),
        ),
    ]
