# Generated by Django 4.0.3 on 2022-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierone',
            name='date_of_investment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
