# Generated by Django 3.2.8 on 2022-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier1', '0002_alter_tierone_date_of_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierone',
            name='earnings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tierone',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tierone',
            name='transction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
