# Generated by Django 3.2.8 on 2022-05-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier1', '0003_auto_20220521_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierone',
            name='status',
            field=models.BooleanField(),
        ),
    ]
