# Generated by Django 3.2.8 on 2022-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier1', '0005_alter_tierone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierone',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
