# Generated by Django 3.2.8 on 2022-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier1', '0010_tierone_date_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierone',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
