# Generated by Django 4.0.3 on 2022-04-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet', models.CharField(blank=True, max_length=500, null=True)),
                ('litecoin_wallet', models.CharField(blank=True, max_length=500, null=True)),
                ('busd_wallet', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
